import { AppknitSDK, SdkExecutionError, SdkGenericErrorCodes } from '@appknit-project/appknit-platform-sdk-v2';
import extension from './index'
const input = {
    "apSelfAssesTaxFlag": "Y",
    "vendorBilledTax": 4,
    "taxedLines": [
        {
            "id": 85009018025633,
            "transactionId": 85009018025629,
            "lineNumber": "2",
            "boundaryOverrideId": 0,
            "customerUsageType": "",
            "entityUseCode": "",
            "description": "",
            "destinationAddressId": 85009018025630,
            "originAddressId": 85009018025631,
            "discountAmount": 0,
            "discountTypeId": 0,
            "exemptAmount": 100,
            "exemptCertId": 0,
            "exemptNo": "",
            "isItemTaxable": false,
            "isSSTP": false,
            "itemCode": "",
            "lineAmount": 100,
            "quantity": 1,
            "ref1": "",
            "ref2": "",
            "reportingDate": "2022-09-07",
            "revAccount": "SERPSOLS-00-110001-000-SERPCONS-0-0-0-0-0",
            "sourcing": "Mixed",
            "tax": 0,
            "taxableAmount": 0,
            "taxCalculated": 10.25,
            "taxCode": "P0000000",
            "taxCodeId": 8087,
            "taxDate": "2022-09-07",
            "taxEngine": "",
            "taxOverrideType": "TaxAmount",
            "businessIdentificationNo": "",
            "taxOverrideAmount": 0,
            "taxOverrideReason": "Tax Amount and Tax Date override",
            "taxIncluded": false,
            "originationDocumentId": "2",
            "details": [
                {
                    "id": 85009018025642,
                    "transactionLineId": 85009018025633,
                    "transactionId": 85009018025629,
                    "addressId": 85009018025631,
                    "country": "US",
                    "region": "CA",
                    "countyFIPS": "",
                    "stateFIPS": "",
                    "exemptAmount": 0,
                    "exemptReasonId": 5,
                    "inState": true,
                    "jurisCode": "06",
                    "jurisName": "CALIFORNIA",
                    "jurisdictionId": 5000531,
                    "signatureCode": "AGAM",
                    "stateAssignedNo": "",
                    "jurisType": "STA",
                    "jurisdictionType": "State",
                    "nonTaxableAmount": 100,
                    "nonTaxableRuleId": 0,
                    "nonTaxableType": "RateRule",
                    "rate": 0.06,
                    "rateRuleId": 2736128,
                    "rateSourceId": 3,
                    "serCode": "",
                    "sourcing": "Origin",
                    "tax": 0,
                    "taxableAmount": 0,
                    "taxType": "ConsumerUse",
                    "taxSubTypeId": "C",
                    "taxTypeGroupId": "SalesAndUse",
                    "taxName": "CA STATE TAX",
                    "taxAuthorityTypeId": 45,
                    "taxRegionId": 4017445,
                    "taxCalculated": 6,
                    "taxOverride": 0,
                    "rateType": "General",
                    "rateTypeCode": "G",
                    "taxableUnits": 0,
                    "nonTaxableUnits": 100,
                    "exemptUnits": 0,
                    "unitOfBasis": "PerCurrencyUnit",
                    "isNonPassThru": false,
                    "isFee": false,
                    "reportingTaxableUnits": 0,
                    "reportingNonTaxableUnits": 100,
                    "reportingExemptUnits": 0,
                    "reportingTax": 0,
                    "reportingTaxCalculated": 6,
                    "liabilityType": "Seller"
                },
                {
                    "id": 85009018025643,
                    "transactionLineId": 85009018025633,
                    "transactionId": 85009018025629,
                    "addressId": 85009018025631,
                    "country": "US",
                    "region": "CA",
                    "countyFIPS": "",
                    "stateFIPS": "",
                    "exemptAmount": 0,
                    "exemptReasonId": 5,
                    "inState": true,
                    "jurisCode": "001",
                    "jurisName": "ALAMEDA",
                    "jurisdictionId": 238,
                    "signatureCode": "AGAO",
                    "stateAssignedNo": "",
                    "jurisType": "CTY",
                    "jurisdictionType": "County",
                    "nonTaxableAmount": 100,
                    "nonTaxableRuleId": 0,
                    "nonTaxableType": "RateRule",
                    "rate": 0.0025,
                    "rateRuleId": 2773384,
                    "rateSourceId": 3,
                    "serCode": "",
                    "sourcing": "Origin",
                    "tax": 0,
                    "taxableAmount": 0,
                    "taxType": "ConsumerUse",
                    "taxSubTypeId": "C",
                    "taxTypeGroupId": "SalesAndUse",
                    "taxName": "CA COUNTY TAX",
                    "taxAuthorityTypeId": 45,
                    "taxRegionId": 4017445,
                    "taxCalculated": 0.25,
                    "taxOverride": 0,
                    "rateType": "General",
                    "rateTypeCode": "G",
                    "taxableUnits": 0,
                    "nonTaxableUnits": 100,
                    "exemptUnits": 0,
                    "unitOfBasis": "PerCurrencyUnit",
                    "isNonPassThru": false,
                    "isFee": false,
                    "reportingTaxableUnits": 0,
                    "reportingNonTaxableUnits": 100,
                    "reportingExemptUnits": 0,
                    "reportingTax": 0,
                    "reportingTaxCalculated": 0.25,
                    "liabilityType": "Seller"
                },
                {
                    "id": 85009018025644,
                    "transactionLineId": 85009018025633,
                    "transactionId": 85009018025629,
                    "addressId": 85009018025630,
                    "country": "US",
                    "region": "CA",
                    "countyFIPS": "",
                    "stateFIPS": "",
                    "exemptAmount": 0,
                    "exemptReasonId": 5,
                    "inState": true,
                    "jurisCode": "EMAK0",
                    "jurisName": "ALAMEDA COUNTY DISTRICT TAX SP",
                    "jurisdictionId": 2001061409,
                    "signatureCode": "EMAK",
                    "stateAssignedNo": "966",
                    "jurisType": "STJ",
                    "jurisdictionType": "Special",
                    "nonTaxableAmount": 100,
                    "nonTaxableRuleId": 0,
                    "nonTaxableType": "RateRule",
                    "rate": 0.03,
                    "rateRuleId": 2744820,
                    "rateSourceId": 3,
                    "serCode": "",
                    "sourcing": "Destination",
                    "tax": 0,
                    "taxableAmount": 0,
                    "taxType": "ConsumerUse",
                    "taxSubTypeId": "C",
                    "taxTypeGroupId": "SalesAndUse",
                    "taxName": "CA SPECIAL TAX",
                    "taxAuthorityTypeId": 45,
                    "taxRegionId": 4017445,
                    "taxCalculated": 3,
                    "taxOverride": 0,
                    "rateType": "General",
                    "rateTypeCode": "G",
                    "taxableUnits": 0,
                    "nonTaxableUnits": 100,
                    "exemptUnits": 0,
                    "unitOfBasis": "PerCurrencyUnit",
                    "isNonPassThru": false,
                    "isFee": false,
                    "reportingTaxableUnits": 0,
                    "reportingNonTaxableUnits": 100,
                    "reportingExemptUnits": 0,
                    "reportingTax": 0,
                    "reportingTaxCalculated": 3,
                    "liabilityType": "Seller"
                },
                {
                    "id": 85009018025645,
                    "transactionLineId": 85009018025633,
                    "transactionId": 85009018025629,
                    "addressId": 85009018025631,
                    "country": "US",
                    "region": "CA",
                    "countyFIPS": "",
                    "stateFIPS": "",
                    "exemptAmount": 0,
                    "exemptReasonId": 5,
                    "inState": true,
                    "jurisCode": "EMSJ0",
                    "jurisName": "ALAMEDA CO LOCAL TAX SL",
                    "jurisdictionId": 2001061755,
                    "signatureCode": "EMSJ",
                    "stateAssignedNo": "01",
                    "jurisType": "STJ",
                    "jurisdictionType": "Special",
                    "nonTaxableAmount": 100,
                    "nonTaxableRuleId": 0,
                    "nonTaxableType": "RateRule",
                    "rate": 0.01,
                    "rateRuleId": 2769213,
                    "rateSourceId": 3,
                    "serCode": "",
                    "sourcing": "Origin",
                    "tax": 0,
                    "taxableAmount": 0,
                    "taxType": "ConsumerUse",
                    "taxSubTypeId": "C",
                    "taxTypeGroupId": "SalesAndUse",
                    "taxName": "CA SPECIAL TAX",
                    "taxAuthorityTypeId": 45,
                    "taxRegionId": 4017445,
                    "taxCalculated": 1,
                    "taxOverride": 0,
                    "rateType": "General",
                    "rateTypeCode": "G",
                    "taxableUnits": 0,
                    "nonTaxableUnits": 100,
                    "exemptUnits": 0,
                    "unitOfBasis": "PerCurrencyUnit",
                    "isNonPassThru": false,
                    "isFee": false,
                    "reportingTaxableUnits": 0,
                    "reportingNonTaxableUnits": 100,
                    "reportingExemptUnits": 0,
                    "reportingTax": 0,
                    "reportingTaxCalculated": 1,
                    "liabilityType": "Seller"
                }
            ],
            "nonPassthroughDetails": [],
            "lineLocationTypes": [
                {
                    "documentLineLocationTypeId": 85009018025636,
                    "documentLineId": 85009018025633,
                    "documentAddressId": 85009018025631,
                    "locationTypeCode": "ShipFrom"
                },
                {
                    "documentLineLocationTypeId": 85009018025637,
                    "documentLineId": 85009018025633,
                    "documentAddressId": 85009018025630,
                    "locationTypeCode": "ShipTo"
                }
            ],
            "userDefinedFields": [
                {
                    "name": "UDF1",
                    "value": "ORACLE"
                }
            ],
            "hsCode": "",
            "costInsuranceFreight": 0,
            "vatCode": "",
            "vatNumberTypeId": 0
        },
        {
            "id": 85009018025634,
            "transactionId": 85009018025629,
            "lineNumber": "1",
            "boundaryOverrideId": 0,
            "customerUsageType": "",
            "entityUseCode": "",
            "description": "",
            "destinationAddressId": 85009018025630,
            "originAddressId": 85009018025631,
            "discountAmount": 0,
            "discountTypeId": 0,
            "exemptAmount": 100,
            "exemptCertId": 0,
            "exemptNo": "",
            "isItemTaxable": false,
            "isSSTP": false,
            "itemCode": "",
            "lineAmount": 100,
            "quantity": 1,
            "ref1": "",
            "ref2": "",
            "reportingDate": "2022-09-07",
            "revAccount": "SERPSOLS-00-110001-000-SERPCONS-0-0-0-0-0",
            "sourcing": "Mixed",
            "tax": 0,
            "taxableAmount": 0,
            "taxCalculated": 10.25,
            "taxCode": "P0000000",
            "taxCodeId": 8087,
            "taxDate": "2022-09-07",
            "taxEngine": "",
            "taxOverrideType": "TaxAmount",
            "businessIdentificationNo": "",
            "taxOverrideAmount": 0,
            "taxOverrideReason": "Tax Amount and Tax Date override",
            "taxIncluded": false,
            "originationDocumentId": "1",
            "details": [
                {
                    "id": 85009018025653,
                    "transactionLineId": 85009018025634,
                    "transactionId": 85009018025629,
                    "addressId": 85009018025631,
                    "country": "US",
                    "region": "CA",
                    "countyFIPS": "",
                    "stateFIPS": "",
                    "exemptAmount": 0,
                    "exemptReasonId": 5,
                    "inState": true,
                    "jurisCode": "06",
                    "jurisName": "CALIFORNIA",
                    "jurisdictionId": 5000531,
                    "signatureCode": "AGAM",
                    "stateAssignedNo": "",
                    "jurisType": "STA",
                    "jurisdictionType": "State",
                    "nonTaxableAmount": 100,
                    "nonTaxableRuleId": 0,
                    "nonTaxableType": "RateRule",
                    "rate": 0.06,
                    "rateRuleId": 2736128,
                    "rateSourceId": 3,
                    "serCode": "",
                    "sourcing": "Origin",
                    "tax": 0,
                    "taxableAmount": 0,
                    "taxType": "ConsumerUse",
                    "taxSubTypeId": "C",
                    "taxTypeGroupId": "SalesAndUse",
                    "taxName": "CA STATE TAX",
                    "taxAuthorityTypeId": 45,
                    "taxRegionId": 4017445,
                    "taxCalculated": 6,
                    "taxOverride": 0,
                    "rateType": "General",
                    "rateTypeCode": "G",
                    "taxableUnits": 0,
                    "nonTaxableUnits": 100,
                    "exemptUnits": 0,
                    "unitOfBasis": "PerCurrencyUnit",
                    "isNonPassThru": false,
                    "isFee": false,
                    "reportingTaxableUnits": 0,
                    "reportingNonTaxableUnits": 100,
                    "reportingExemptUnits": 0,
                    "reportingTax": 0,
                    "reportingTaxCalculated": 6,
                    "liabilityType": "Seller"
                },
                {
                    "id": 85009018025654,
                    "transactionLineId": 85009018025634,
                    "transactionId": 85009018025629,
                    "addressId": 85009018025631,
                    "country": "US",
                    "region": "CA",
                    "countyFIPS": "",
                    "stateFIPS": "",
                    "exemptAmount": 0,
                    "exemptReasonId": 5,
                    "inState": true,
                    "jurisCode": "001",
                    "jurisName": "ALAMEDA",
                    "jurisdictionId": 238,
                    "signatureCode": "AGAO",
                    "stateAssignedNo": "",
                    "jurisType": "CTY",
                    "jurisdictionType": "County",
                    "nonTaxableAmount": 100,
                    "nonTaxableRuleId": 0,
                    "nonTaxableType": "RateRule",
                    "rate": 0.0025,
                    "rateRuleId": 2773384,
                    "rateSourceId": 3,
                    "serCode": "",
                    "sourcing": "Origin",
                    "tax": 0,
                    "taxableAmount": 0,
                    "taxType": "ConsumerUse",
                    "taxSubTypeId": "C",
                    "taxTypeGroupId": "SalesAndUse",
                    "taxName": "CA COUNTY TAX",
                    "taxAuthorityTypeId": 45,
                    "taxRegionId": 4017445,
                    "taxCalculated": 0.25,
                    "taxOverride": 0,
                    "rateType": "General",
                    "rateTypeCode": "G",
                    "taxableUnits": 0,
                    "nonTaxableUnits": 100,
                    "exemptUnits": 0,
                    "unitOfBasis": "PerCurrencyUnit",
                    "isNonPassThru": false,
                    "isFee": false,
                    "reportingTaxableUnits": 0,
                    "reportingNonTaxableUnits": 100,
                    "reportingExemptUnits": 0,
                    "reportingTax": 0,
                    "reportingTaxCalculated": 0.25,
                    "liabilityType": "Seller"
                },
                {
                    "id": 85009018025655,
                    "transactionLineId": 85009018025634,
                    "transactionId": 85009018025629,
                    "addressId": 85009018025630,
                    "country": "US",
                    "region": "CA",
                    "countyFIPS": "",
                    "stateFIPS": "",
                    "exemptAmount": 0,
                    "exemptReasonId": 5,
                    "inState": true,
                    "jurisCode": "EMAK0",
                    "jurisName": "ALAMEDA COUNTY DISTRICT TAX SP",
                    "jurisdictionId": 2001061409,
                    "signatureCode": "EMAK",
                    "stateAssignedNo": "966",
                    "jurisType": "STJ",
                    "jurisdictionType": "Special",
                    "nonTaxableAmount": 100,
                    "nonTaxableRuleId": 0,
                    "nonTaxableType": "RateRule",
                    "rate": 0.03,
                    "rateRuleId": 2744820,
                    "rateSourceId": 3,
                    "serCode": "",
                    "sourcing": "Destination",
                    "tax": 0,
                    "taxableAmount": 0,
                    "taxType": "ConsumerUse",
                    "taxSubTypeId": "C",
                    "taxTypeGroupId": "SalesAndUse",
                    "taxName": "CA SPECIAL TAX",
                    "taxAuthorityTypeId": 45,
                    "taxRegionId": 4017445,
                    "taxCalculated": 3,
                    "taxOverride": 0,
                    "rateType": "General",
                    "rateTypeCode": "G",
                    "taxableUnits": 0,
                    "nonTaxableUnits": 100,
                    "exemptUnits": 0,
                    "unitOfBasis": "PerCurrencyUnit",
                    "isNonPassThru": false,
                    "isFee": false,
                    "reportingTaxableUnits": 0,
                    "reportingNonTaxableUnits": 100,
                    "reportingExemptUnits": 0,
                    "reportingTax": 0,
                    "reportingTaxCalculated": 3,
                    "liabilityType": "Seller"
                },
                {
                    "id": 85009018025656,
                    "transactionLineId": 85009018025634,
                    "transactionId": 85009018025629,
                    "addressId": 85009018025631,
                    "country": "US",
                    "region": "CA",
                    "countyFIPS": "",
                    "stateFIPS": "",
                    "exemptAmount": 0,
                    "exemptReasonId": 5,
                    "inState": true,
                    "jurisCode": "EMSJ0",
                    "jurisName": "ALAMEDA CO LOCAL TAX SL",
                    "jurisdictionId": 2001061755,
                    "signatureCode": "EMSJ",
                    "stateAssignedNo": "01",
                    "jurisType": "STJ",
                    "jurisdictionType": "Special",
                    "nonTaxableAmount": 100,
                    "nonTaxableRuleId": 0,
                    "nonTaxableType": "RateRule",
                    "rate": 0.01,
                    "rateRuleId": 2769213,
                    "rateSourceId": 3,
                    "serCode": "",
                    "sourcing": "Origin",
                    "tax": 0,
                    "taxableAmount": 0,
                    "taxType": "ConsumerUse",
                    "taxSubTypeId": "C",
                    "taxTypeGroupId": "SalesAndUse",
                    "taxName": "CA SPECIAL TAX",
                    "taxAuthorityTypeId": 45,
                    "taxRegionId": 4017445,
                    "taxCalculated": 1,
                    "taxOverride": 0,
                    "rateType": "General",
                    "rateTypeCode": "G",
                    "taxableUnits": 0,
                    "nonTaxableUnits": 100,
                    "exemptUnits": 0,
                    "unitOfBasis": "PerCurrencyUnit",
                    "isNonPassThru": false,
                    "isFee": false,
                    "reportingTaxableUnits": 0,
                    "reportingNonTaxableUnits": 100,
                    "reportingExemptUnits": 0,
                    "reportingTax": 0,
                    "reportingTaxCalculated": 1,
                    "liabilityType": "Seller"
                }
            ],
            "nonPassthroughDetails": [],
            "lineLocationTypes": [
                {
                    "documentLineLocationTypeId": 85009018025647,
                    "documentLineId": 85009018025634,
                    "documentAddressId": 85009018025631,
                    "locationTypeCode": "ShipFrom"
                },
                {
                    "documentLineLocationTypeId": 85009018025648,
                    "documentLineId": 85009018025634,
                    "documentAddressId": 85009018025630,
                    "locationTypeCode": "ShipTo"
                }
            ],
            "userDefinedFields": [
                {
                    "name": "UDF1",
                    "value": "ORACLE"
                }
            ],
            "hsCode": "",
            "costInsuranceFreight": 0,
            "vatCode": "",
            "vatNumberTypeId": 0
        }
    ],
    "apTolerances": {
        "tolerancePct": null,
        "toleranceAmt": null
    }
}
let queryCounter = 1
const sdk = new AppknitSDK(null, null, {
    // @ts-ignore
    adhocDataProvider: {
        queryDataRecords: async (query)=>{
            // console.log(JSON.stringify(query, null, 2))
            if (queryCounter === 1) {
                queryCounter = queryCounter + 1
                return [
                    {
                        ATX_TAX_CODE: 'STATE',
                        ATX_RATE_CODE: 'STANDARD',
                        ATX_TAX_STATUS_CODE: 'STANDARD',
                        ATX_JURISDICTION_CODE: '-ST-050000000',
                    }
                ]  
            }
            if (queryCounter === 2) {
                queryCounter = queryCounter + 1
                return [
                    {
                        ATX_TAX_CODE: 'COUNTY',
                        ATX_RATE_CODE: 'STANDARD',
                        ATX_TAX_STATUS_CODE: 'STANDARD',
                        ATX_JURISDICTION_CODE: '-CO-050010000',
                    }
                ]  
            }
            return [
                {
                    ATX_TAX_CODE: 'SPECIAL',
                    ATX_RATE_CODE: '_SPECIAL_RATE',
                    ATX_TAX_STATUS_CODE: 'STANDARD',
                    ATX_JURISDICTION_CODE: '-SPECIAL',
                }
            ]
        },
    }
})
extension.flowFunctions.proRateTaxes.js(sdk, input).then(result=>console.log(result))

// extension.flowFunctions.mapFusionSoapRequestV2.js(sdk, {body: triggerBody}).then(result=>console.log(result))